rootfs_ipk: don't emit error code when ONLINE_PACKAGE_MANAGEMENT is really none
* currently do_rootfs fails when it's "none", because that test returns
  exit code '1':
  | log_check: Using /OE/tmpdir-shr/work/spitz-oe-linux-gnueabi/initramfs-kexecboot-klibc-image-1.0-r0/temp/log.do_rootfs.21324 as logfile
  | Logfile is clean
  | + rm -rf /OE/tmpdir-shr/rootfs/initramfs-kexecboot-klibc-image-tmp
  | + '[' none '!=' none ']'
  NOTE: package initramfs-kexecboot-klibc-image-1.0-r0: task do_rootfs: Failed
  ERROR: Function 'do_rootfs' failed (see /OE/tmpdir-shr/work/spitz-oe-linux-gnueabi/initramfs-kexecboot-klibc-image-1.0-r0/temp/log.do_rootfs.21324 for further information)
  ERROR: Task 1356 (/OE/dev/recipes/images/initramfs-kexecboot-klibc-image.bb, do_rootfs) failed with exit code '1'
  ERROR: '/OE/dev/recipes/images/initramfs-kexecboot-klibc-image.bb' failed

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>