lowpan-tools_git.bb: Fix SRC_URI and update SRCREV.
The old rev did not even build and to checkout a newer one we need to follow the
URI changes rom upstream:

| cc1: warnings being treated as errors
| izconfig.c: In function 'do_set_short':
| izconfig.c:186: error: dereferencing pointer 'sa' does break strict-aliasing rules
| izconfig.c:179: error: dereferencing pointer 'sa' does break strict-aliasing rules