distro-version, kaeilos-version: don't export METADATA_BRANCH and METADATA_REVISION
Causes infinite recursion, which may look like this:

NOTE: <type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object while evaluating: ${@base_get_scm_branch(d)}

Or this:

Traceback (most recent call last):
 File "/home/grg/oe2/bitbake/lib/bb/server/none.py", line 128, in idle_commands
   retval = function(self, data, False)
 File "/home/grg/oe2/bitbake/lib/bb/cooker.py", line 716, in buildTargetsIdle
   retval = rq.execute_runqueue()
 File "/home/grg/oe2/bitbake/lib/bb/runqueue.py", line 877, in execute_runqueue
   self.execute_runqueue_internal()
 File "/home/grg/oe2/bitbake/lib/bb/runqueue.py", line 992, in execute_runqueue_internal
   self.build_pipes[pipe].read()
 File "/home/grg/oe2/bitbake/lib/bb/runqueue.py", line 1227, in read
   bb.event.fire_from_worker(self.queue[:index+8], self.d)
 File "/home/grg/oe2/bitbake/lib/bb/event.py", line 137, in fire_from_worker
   event = pickle.loads(event[7:-8])
 File "/usr/lib64/python2.6/pickle.py", line 1374, in loads
   return Unpickler(file).load()
 File "/usr/lib64/python2.6/pickle.py", line 858, in load
   dispatch[key](self)
 File "/usr/lib64/python2.6/pickle.py", line 966, in load_string
   raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Acked-by: Chris Larson <chris_larson@mentor.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>