acpid-1.0.10: fix compiler warning on some platforms
Task compile fails with the following error.

| i686-angstrom-linux-gcc -march=pentiumpro --sysroot=/oe/build-vmc16/tmp/sysroots/i686-angstrom-linux -W -Wall -Werror -Wundef -Wshadow -D_GNU_SOURCE -O2 -g -DVERSION="\"1.0.10\""   -c -o sock.o sock.c
| cc1: warnings being treated as errors
| libnetlink.c: In function 'addraw_l':
| libnetlink.c:521:56: error: comparison between signed and unsigned integer expressions

Adding a missing cast fixes this problem.

Signed-off-by: Christian Betz <christian.betz@gmail.com>
Tested on `i686` by: Søren Holm <sgh@sgh.dk>
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>