tangogps.inc: depend on libexif
If we don't depend on libexif we have that error:
| In file included from geo_photos.c:12:
| exif.h:1:31: error: libexif/exif-data.h: No such file or directory
| In file included from geo_photos.c:12:
| exif.h:3: error: expected ')' before '*' token
| exif.h:4: error: expected ')' before '*' token
| geo_photos.c: In function 'geo_photo_dialog_image_data_next':
| geo_photos.c:527: error: 'ExifData' undeclared (first use in this function)
| geo_photos.c:527: error: (Each undeclared identifier is reported only once
| geo_photos.c:527: error: for each function it appears in.)
| geo_photos.c:527: error: 'ed' undeclared (first use in this function)
| geo_photos.c:609: warning: implicit declaration of function 'exif_data_new_from_file'
| geo_photos.c:615: warning: implicit declaration of function 'show_tag'
| geo_photos.c:615: error: 'EXIF_IFD_0' undeclared (first use in this function)
| geo_photos.c:615: error: 'EXIF_TAG_DATE_TIME' undeclared (first use in this function)
| geo_photos.c:615: warning: assignment makes pointer from integer without a cast
| geo_photos.c:616: warning: implicit declaration of function 'strptime'
| make[2]: *** [geo_photos.o] Error 1
| make[2]: Leaving directory `/home/embedded/oetmp_bug/work/armv6-angstrom-linux-gnueabi/tangogps-0.9.6-r0/tangogps-0.9.6/src'
| make[1]: *** [all-recursive] Error 1
| make[1]: Leaving directory `/home/embedded/oetmp_bug/work/armv6-angstrom-linux-gnueabi/tangogps-0.9.6-r0/tangogps-0.9.6'
| make: *** [all] Error 2
| FATAL: oe_runmake failed