xmlrpc-c_1.06.41.bb: QA issue with staging (workdir) for .la files in xmlrpc-c package
I think I've solved this problem. Half of my solution is to modify the
xmlrpc-c package's Make file to pass the library file names directly
instead of using the "-L<directory> -l<name>" method. The other half
is to force it to use the newer Libtool version instead of its own.
See patch #1 attached, though I'm not really an expert on Libtool or
Open embedded, so I can't say if it might break something else, and I
haven't even tested out the packages I built yet.

Adds a patch to avoid using -L link flags, and forces the Make files to use a
newer external Libtool.

Fix do_configure to bypass reconfigure but still generate libtool

Fix below messages

NOTE: Multiple libraries (libxmlrpc_server_cgi.so.3,
libxmlrpc_util.so.3, libxmlrpc_client.so.3, libxmlrpc_abyss.so.3,
libxmlrpc_server_abyss.so.3, libxmlrpc_server.so.3, libxmlrpc.so.3)
found and LEAD_SONAME not defined

ERROR: QA Issue with xmlrpc-c: No GNU_HASH in the elf binary:
'/scratch/oe/work/armv7a-oe-linux-gnueabi/xmlrpc-c-1.06.41-r1/packages-split/xmlrpc-c/usr/lib/libxmlrpc_server_cgi.so.3.6.15'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Panter <vadmium+floss@gmail.com>