opkg-utils: bump SRCREV to pick up subprocess.check_output fixes
There were few breakages related to subprocess.check_output() with Python
versions prior to 2.7 (although I had them even with 2.7.3), most notably
in opkg-make-index:

Log data follows:
| + do_package_update_index_ipk
| + set -x
| + ipkgarchs='all any noarch arm  armv4 armv4t armv5te armv6 armv7 armv7a am37x-evm'
| + '[' '!' -z '' ']'
| + mkdir -p /OE/deploy/glibc/ipk
| + touch /OE/deploy/glibc/ipk/Packages
| + opkg-make-index -r /OE/deploy/glibc/ipk/Packages -p /OE/deploy/glibc/ipk/Packages -l /OE/deploy/glibc/ipk/Packages.filelist -m /OE/deploy/glibc/ipk
| Traceback (most recent call last):
|   File "/OE/sysroots/x86_64-linux/usr/bin/opkg-make-index", line 189, in <module>
|     rc = subprocess.check_output(gzip_cmd, shell=True)
| AttributeError: 'module' object has no attribute 'check_output'
NOTE: package my-image-1.0-r0: task do_package_update_index_ipk: Failed

The following fixes are required:
http://git.yoctoproject.org/cgit/cgit.cgi/opkg-utils/commit/?id=423ecd36b4782327c16f516885d1248249c7724a
http://git.yoctoproject.org/cgit/cgit.cgi/opkg-utils/commit/?id=49cc783d8e0415059d126ae22c892988717ffda7

Signed-off-by: Denys Dmytriyenko <denys@ti.com>