galago: move to obsolete.
libgalago doesn't build, and presumably hasn't since dbus 0.92 was in the tree.

| ../libgalago/.libs/libgalago.so: undefined reference to `dbus_connection_disconnect'
| collect2: ld returned 1 exit status
| make[2]: *** [presence-feed] Error 1

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Acked-by: Frans Meulenbroeks <fransmeulenbroeks@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>