pf-ring: update to r4384 to fix `pf_ring.c:329:3: error: implicit declaration of function 'vmalloc_32'`
Task `compile` failed with the following error.

	[…]
	| /oe/build-minimal-eglibc/minimal-dev/work/beagleboard-oe-linux-gnueabi/pf-ring-4.4.0+svnr4326-r90/kernel/pf_ring.c: In function 'rvmalloc':
	| /oe/build-minimal-eglibc/minimal-dev/work/beagleboard-oe-linux-gnueabi/pf-ring-4.4.0+svnr4326-r90/kernel/pf_ring.c:329:3: error: implicit declaration of function 'vmalloc_32'
	| /oe/build-minimal-eglibc/minimal-dev/work/beagleboard-oe-linux-gnueabi/pf-ring-4.4.0+svnr4326-r90/kernel/pf_ring.c:329:7: warning: assignment makes pointer from integer without a cast
	| /oe/build-minimal-eglibc/minimal-dev/work/beagleboard-oe-linux-gnueabi/pf-ring-4.4.0+svnr4326-r90/kernel/pf_ring.c: In function 'rvfree':
	| /oe/build-minimal-eglibc/minimal-dev/work/beagleboard-oe-linux-gnueabi/pf-ring-4.4.0+svnr4326-r90/kernel/pf_ring.c:377:3: error: implicit declaration of function 'vfree'
	[…]

	Build Configuration:
	BB_VERSION        = "1.10.0"
	METADATA_BRANCH   = "org.openembedded.dev"
	METADATA_REVISION = "8fc09c071a6fba0766c3b002209c758572298d26"
	TARGET_ARCH       = "arm"
	TARGET_OS         = "linux-gnueabi"
	MACHINE           = "beagleboard"
	DISTRO            = "minimal"
	DISTRO_VERSION    = "dev-snapshot-20101103"
	TARGET_FPU        = "hard"

Updating to revision 4384 fixes the problem. It was build tested with `minimal`, `minimal-uclibc`, `angstrom-2008.1` and `angstrom-2010.x` for `MACHINE = "beagleboard"`.

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Roman I Khimov <khimov@altell.ru>
Signed-off-by: Roman I Khimov <khimov@altell.ru>