imlib_1.9.15, qiv_1.9: move to obsolete.
Motivation for removal:
ERROR: QA Issue with staging: imlib.pc failed sanity test (tmpdir) in path /mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/lib/pkgconfig

This 3 year old qiv recipe is the only in tree user of imlib1. Newer
versions of qiv which use imlib2 are available from http://spiegl.de/qiv/

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>