xbmc_svn: apply upstream patch complete replacement of liblzo with liblzo2, linux was already liblzo2
Task compile fails with /bin/grep: /usr/lib/libz.la: No such file or directory.

	| arm-angstrom-linux-gnueabi-g++ -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -mno-thumb -isystem/oe/build/angstrom-dev/sysroots/armv7a
	-angstrom-linux-gnueabi/usr/include -fexpensive-optimizations -frename-registers -fomit-frame-pointer -O2 -ggdb2 -fpermissive -fvisibility-inlines-hidden -fPIC -DPIC -D_REENTRANT -
	D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -g -D_DEBUG -Wall -O2 -mfloat-abi=softfp -mno-apcs-stack-check -Wa,-march=armv7a -mcpu=cortex-a8 -mfpu=neon -mvectorize-with-neon-quad -
	isystem/oe/build/angstrom-dev/sysroots/armv7a-angstrom-linux-gnueabi/usr/include -fexpensive-optimizations -frename-registers -fomit-frame-pointer -O2 -ggdb2 -fpermissive
	 -fvisibility-inlines-hidden -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -g -D_DEBUG -Wall -O2 -mfloat-abi=softfp -mno-apcs-stack-check -Wa,-march=armv7a
	-mcpu=cortex-a8 -mfpu=neon -mvectorize-with-neon-quad -isystem/oe/build/angstrom-dev/sysroots/armv7a-angstrom-linux-gnueabi/usr/include -fexpensive-optimizations -frename
	-registers -fomit-frame-pointer -O2 -ggdb2 -fpermissive -fvisibility-inlines-hidden -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -g -D_DEBUG -Wall -O2 -mfl
	oat-abi=softfp -mno-apcs-stack-check -Wa,-march=armv7a -mcpu=cortex-a8 -mfpu=neon -mvectorize-with-neon-quad SDL_anigif.o XBTFWriter.o XBMCTex.o ../../guilib/XBTF.o      -L/home/pa
	ul/oe/build/angstrom-dev/sysroots/armv7a-angstrom-linux-gnueabi/usr/lib -Wl,-rpath-link,/oe/build/angstrom-dev/sysroots/armv7a-angstrom-linux-gnueabi/usr/lib -Wl,-O1 -Wl,
	--hash-style=gnu ../../xbmc/lib/libsquish/libsquish-arm.a -lSDL_image -lSDL -llzo2 -o TexturePacker
	| XBMCTex.o: In function `main':
	| /oe/build/angstrom-dev/work/armv7a-angstrom-linux-gnueabi/xbmc-10.05-r9+gitr0+e2ab481ebe964321c358ab9d6402088c714adcbe/git/tools/TexturePacker/XBMCTex.cpp:394: undefined reference to `__lzo_init2'
	| collect2: ld returned 1 exit status
	| make[1]: *** [TexturePacker] Error 1
	| make[1]: Leaving directory `/oe/build/angstrom-dev/work/armv7a-angstrom-linux-gnueabi/xbmc-10.05-r9+gitr0+e2ab481ebe964321c358ab9d6402088c714adcbe/git/tools/TexturePacker'
	| make: *** [tools/TexturePacker/TexturePacker] Error 2
	| FATAL: oe_runmake failed
	| ERROR: Function do_compile failed
	NOTE: package xbmc-10.05-r9+gitr0+e2ab481ebe964321c358ab9d6402088c714adcbe: task do_compile: Failed
	ERROR: TaskFailed event exception, aborting
	ERROR: Build of /oe/openembedded/recipes/xbmc/xbmc_svn.bb do_compile failed
	ERROR: Task 13 (/oe/openembedded/recipes/xbmc/xbmc_svn.bb, do_compile) failed with 256
	ERROR: '/oe/openembedded/recipes/xbmc/xbmc_svn.bb' failed
	ERROR: '/oe/openembedded/recipes/xbmc/xbmc_svn.bb' failed
	ERROR: '/oe/openembedded/recipes/xbmc/xbmc_svn.bb' failed

A fix was provided upstream in changeset 35484 [1][2] and on the list by Eric Colleu [3].

This patch is build tested with `angstrom-2008.1` and `minimal`.

[1] http://trac.xbmc.org/changeset/35484
[2] https://github.com/xbmc/xbmc/commit/9e765ccae4ef9753c94b793f44931d84f65ca99c
[3] http://lists.linuxtogo.org/pipermail/openembedded-devel/2010-November/027418.html

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Khem Raj <raj.khem@gmail.com>