findutils: fix update-alternatives and native packages
Sync with org.oe.dev (fix for update-alternatives postinst, prerm).
Move update-alternatives logic to findutils-alternatives.inc which is not included in -native packages.
Patch mkinstalldirs.patch is needed also for findutils-native_4.2.29.
Remove version 4.4 as there is no tarball upstream (it's 4.4.0 actually).
Add latest version 4.4.2, but don't prefer it now as it's not compatible with shr preferred old glibc 2.6.1 (staging/armv4t-angstrom-linux-gnueabi/usr/include/stdio.h:654: error: conflicting types for 'rpl_fseeko')

Signed-off-by: Klaus Kurzmann <mok@fluxnetz.de>