gnutls-2.10.4: add missing quote to PR
* is something wrong with parser in bitbake master? IIRC we had
  parse exceptions before for similar typos
* missing quote produces not so nice error like this
  NOTE: Running task 1010 of 1049 (ID: 31, /OE/dev/recipes/gnutls/gnutls_2.10.4.bb, do_setscene)
  NOTE: package gnutls-2.10.4-"r11.2: task do_setscene: Started
  ERROR: Error in compiling python function in /OE/dev/recipes/gnutls/gnutls_2.10.4.bb
  ERROR: invalid syntax (packagestage_scenefunc, line 13)
  ERROR: The lines leading to this error were:
  ERROR:  13:SyntaxError:'    stagepkg = bb.data.expand("/OE/tmpdir-shr/pstage/shreglibc/staging-gnutls-armv4t-oe-linux-gnueabi_2.10.4-"r11.2_armv4t-linux-gnueabi.ipk", d)'
  ERROR:      0009:    removepkg = bb.data.expand("staging-gnutls-armv4t-oe-linux-gnueabi", d)
  ERROR:      0010:
  ERROR:      0011:    pstage_cleanpackage(removepkg, d)
  ERROR:      0012:
  ERROR:  *** 0013:    stagepkg = bb.data.expand("/OE/tmpdir-shr/pstage/shreglibc/staging-gnutls-armv4t-oe-linux-gnueabi_2.10.4-"r11.2_armv4t-linux-gnueabi.ipk", d)
  ERROR:      0014:    if not os.path.exists(stagepkg):
  ERROR:      0015:        staging_fetch(stagepkg, d)
  ERROR:      0016:
  ERROR:      0017:    if os.path.exists(stagepkg):
  ERROR: Function 'packagestage_scenefunc' failed
  ERROR: Logfile of failure stored in: /OE/tmpdir-shr/work/armv4t-oe-linux-gnueabi/gnutls-2.10.4-"r11.2/temp/log.do_setscene.15953

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>