Change to MOC 2.4.4; fixes issue with ltdl library
See attached patch file
-Martin
>From 30689fe0e23b189b7da8bbf461676990a2bdec00 Mon Sep 17 00:00:00 2001
From: Martin Panter <vadmium à gmail.com>
Date: Fri, 24 Dec 2010 05:39:15 +0000
Subject: [PATCH 1/3] MOC: Change to 2.4.4; fixes issue with ltdl library

Version 2.4.3 would give lots of complaints compiling ltdl.c, for instance

ltdl.c:863:31: error: 'LTDL_OBJDIR' undeclared here (not in a function)

Also changed to Source forge mirror

Signed-off-by: Khem Raj <raj.khem@gmail.com>