busybox-1.13.2: fix parallel build failing on appletlib
libbb/appletlib.o depends on generated headers, build can fail with

libbb/appletlib.c:53:27: error: applet_tables.h: No such file or directory

if that dependency is not taken into account