ltp-20090131: Added upstream fix for missing non-x86 syscalls.
This fixes errors for powerpc targets (and likely other targets as well),
such as:

dup3_01.c:74:4: error: #error "need __NR_dup3"

Signed-off-by: Leon Woestenberg <leon@sidebranch.com>