obex-data-server: fix compile error, add missing dependency on gtk+
This patch fixes this compile error:
ods-imaging-helpers.c:32:35: error: gdk-pixbuf/gdk-pixbuf.h: No such file or directory

Signed-off-by: Petr Štetiar <ynezz@true.cz>