gob2 and gob2-native: delete version 2.0.14
Without that the old(2.0.14) version get chosen for
  native, which makes gmpc fail to compile:
  From #gmpc on Freenode on irc:
    Mar 23 12:33:02 <DaveDavenport>	GNUtoo|bug20: I t hink you need to update gob2
    Mar 23 12:33:09 <DaveDavenport>	there was a bug in one of the releases
    Mar 23 12:33:23 <GNUtoo|bug20>	ok
    Mar 23 12:33:24 <DaveDavenport>	that it created the wrong namespaces because of a stupid buffer overflow
The result beeing the following compilation failure:
  ./gmpc-meta-watcher.h:57:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
where the line 57 is:
  GmpcMetaWatcher *       gmpc_meta_watcher_new   (void);'
with GmpcMetaWatcher beeing defined nowhere in the .c or .h source files

gob2 2.0.14 is also deleted by this commit:
From #oe on Freenode on irc:
  Mar 23 12:47:13 <GNUtoo|bug20>	I remove the normal non-native one too?
  Mar 23 12:47:18 <eFfeM_work>	yes please

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>