prboom_2.5.0.bb: fix compilation failure due to undefined references.
Need to #define _GNU_SOURCE for sched.h to define CPU_ZERO/CPU_SET.

 SDL/libsdldoom.a(i_system.o): In function `I_SetAffinityMask':
| i_system.c:(.text+0x7d4): undefined reference to `CPU_ZERO'
| i_system.c:(.text+0x7e8): undefined reference to `CPU_SET'
| collect2: ld returned 1 exit status

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Acked-by: Frans Meulenbroeks <fransmeulenbroeks@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>