strace: Fix build on mips{, el} when DISTRO_FEATURES lacks "largefile".
While here,
 - make 4.5.20 the default for mips instead of 4.5.18.
 - Fix LICENSE fields.

| mipsel-oe-linux-uclibc-gcc -march=mips32 -Wall -isystem/mnt/oe/tmp/sysroots/mipsel-oe-linux-uclibc/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os  -L/mnt/oe/tmp/sysroots/mipsel-oe-linux-uclibc/lib -Wl,-rpath-link,/mnt/oe/tmp/sysroots/mipsel-oe-linux-uclibc/lib -Wl,-O1 -o strace strace.o syscall.o count.o util.o desc.o file.o ipc.o io.o ioctl.o mem.o net.o process.o bjm.o quota.o resource.o signal.o sock.o system.o term.o time.o proc.o scsi.o stream.o
| syscall.o:(.data.rel.ro+0x14904): undefined reference to `sys_truncate64'
| syscall.o:(.data.rel.ro+0x14918): undefined reference to `sys_ftruncate64'
| syscall.o:(.data.rel.ro+0x149a4): undefined reference to `sys_getdents64'
| syscall.o:(.data.rel.ro+0x14c74): undefined reference to `sys_statfs64'
| syscall.o:(.data.rel.ro+0x14c88): undefined reference to `sys_fstatfs64'
| collect2: ld returned 1 exit status
| make[1]: *** [strace] Error 1

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>