glib-2.0_2.26.1: remove `DEFAULT_PREFERENCE = "-1"`
Since commit 07d94e [1] (upstream 2729be [2]) task `configure` of `libfso-glib` fails with the following error, since GLib 2.26 is needed and Minimal and Minimal uClibc just provide GLib 2.24 since `glib-2.0_2.26.1.bb` has `DEFAULT_PREFERENCE = "-1"` set.

	checking pkg-config is at least version 0.9.0... yes
	checking for VALA_DBUS_BINDING_TOOL... yes
	checking for SPECS... yes
	checking for DEPS... configure: error: Package requirements (glib-2.0 >= 2.26.0
		      gobject-2.0 >= 2.26.0
		      gio-2.0 >= 2.26.0
		      gthread-2.0 >= 2.26.0) were not met:

	Requested 'glib-2.0 >= 2.26.0' but version of GLib is 2.24.1
	Requested 'gobject-2.0 >= 2.26.0' but version of GObject is 2.24.1
	Requested 'gio-2.0 >= 2.26.0' but version of GIO is 2.24.1
	Requested 'gthread-2.0 >= 2.26.0' but version of GThread is 2.24.1

	Consider adjusting the PKG_CONFIG_PATH environment variable if you
	installed software in a non-standard prefix.

	Alternatively, you may set the environment variables DEPS_CFLAGS
	and DEPS_LIBS to avoid the need to call pkg-config.
	See the pkg-config man page for more details.

	ERROR: Function do_configure failed

Other packages from the freesmartphone.org API reference implementation will also require GLib 2.26 in the future.

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?h=org.openembedded.dev&id=07d94ebc8fd3d21fa83fb13fdf511ac008c316e6
[2] http://git.freesmartphone.org/?p=libfso-glib.git;a=commit;h=2729be7c82a676455f93d201b0d0255ad7e139ba
[3] http://git.freesmartphone.org/?p=cornucopia.git;a=commit;h=709ef63eab6eb9736c15e6731a50de4ccbb3613c

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Eric Bénard <eric@eukrea.com>
Signed-off-by: Eric Bénard <eric@eukrea.com>