omapfbplay: move patch to new location after switch to Libav
This patch fixes up commit 692d43ee [1]

        commit 692d43eeb6596df52b5984ae1bd14739f9ec9e0f
        Author: Koen Kooi <koen@openembedded.org>
        Date:   Mon Mar 28 15:47:23 2011 +0200

                  libav: add proper recipe for git version
                  omapfbplay: switch to libav

which did not move the patch referenced in the recipe to the new location.

        NOTE: package omapfbplay-0.0+r30+gitr34293052c5a2ae328eac6903512e6b4ce19b5639-r30: task do_patch: Started
        ERROR: [Errno 2] No such file or directory: '/oe/openembedded/recipes/libav/./omapfbplay-errorhandling.patch'
        NOTE: package omapfbplay-0.0+r30+gitr34293052c5a2ae328eac6903512e6b4ce19b5639-r30: task patch_do_patch: Failed

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=692d43eeb6596df52b5984ae1bd14739f9ec9e0f

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>