eet: depend on gnutls(else it fails to compile)
If we don't depend on gnutls we have:
|   CC     libeet_la-eet_connection.lo
| eet_lib.c:50:28: fatal error: gnutls/gnutls.h: No such file or directory