fix bitbake ERRORS for machine not having virtual/egl
* several recipes depend on virtual/egl which currently has only one
provider : powervr-drivers/libgles-omap. This provider sets
COMPATIBLE_MACHINE to a few TI based machines.
When building for machines which don't provide virtual/egl, we get
the following errors :
ERROR: '['path_to/openembedded/recipes/qt4/qt4-embedded-gles_4.6.3.bb']'
      RDEPENDS/RRECOMMENDS or otherwise requires the runtime entity
     'qt4-embedded-gles' but it wasn't found in any PACKAGE or RPROVIDES
     variables of any buildable targets.
ERROR: '[]' RDEPENDS/RRECOMMENDS or otherwise requires the runtime
     entity 'virtual/egl' but it wasn't found in any PACKAGE or RPROVIDES
     variables

* This patch creates a egl.inc which contains the compatible machines for
recipes depending on virtual/egl and thus will workaround this error.

Signed-off-by: Eric Bénard <eric@eukrea.com>
Acked-by: Khem Raj <raj.khem@gmail.com>
Acked-by: Frans Meulenbroeks <fransmeulenbroeks@gmail.com>