gnash : add 0.8.8 version
The 0.8.8 version fixes youtube.

Note that I had to add one more include:
  -I${STAGING_INCDIR}/cairo
Because gnash didn't find cairo:
  | ../sysroots/armv7a-oe-linux-gnueabi/usr/include/gtk-2.0/gdk/gdkscreen.h:31:19: fatal error: cairo.h: No such file or directory
Note that gnashes disables pkg-config during cross-compilation:
  Nov 19 18:09:46 <strk>  IIRC we _never_ use pkgconfig when crossbuilding
From #gnash in Freenode on irc.

I also had to add that:
  --with-npapi-plugindir=${libdir}/mozilla/plugins \
else the plugin would have been installed in:
  image/usr/lib64/mozilla/plugins/libgnashplugin.so
which is a path made using the host libdir(I've a 64bit buildhost)

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>