python-pycairo_1.8.0: remove `DEFAULT_PREFERENCE = "-1"`
Cairo 1.8 is available for some time and ?ngström and other distributions have pinned this Pycairo version for quite some time.

Build tested with Minimal and Minimal uClibc.

	Build Configuration:
	BB_VERSION        = "1.10.0"
	METADATA_BRANCH   = "org.openembedded.dev"
	METADATA_REVISION = "977d4dd"
	TARGET_ARCH       = "arm"
	TARGET_OS         = "linux-gnueabi"
	MACHINE           = "beagleboard"
	DISTRO            = "minimal"
	DISTRO_VERSION    = "dev-snapshot-20101217"
	TARGET_FPU        = "hard"

	Build Configuration:
	BB_VERSION        = "1.10.0"
	METADATA_BRANCH   = "org.openembedded.dev"
	METADATA_REVISION = "977d4dd"
	TARGET_ARCH       = "arm"
	TARGET_OS         = "linux-uclibceabi"
	MACHINE           = "beagleboard"
	DISTRO            = "minimal-uclibc"
	DISTRO_VERSION    = "dev-snapshot-20101217"
	TARGET_FPU        = "hard"

`python-pygtk_2.16.0.bb` does not build with `python-pycairo_1.4.0` because it does not put its package config files in `sysroots`.

	checking for ATK... yes
	checking for PANGO... yes
	checking for codegen... /oe/build-minimal-eglibc/minimal-dev/sysroots/armv7a-oe-linux-gnueabi/usr/share/pygobject/2.0/codegen
	checking for PYCAIRO... no
	no
	not checking for gtk due to missing pycairo
	checking for GDK target... x11
	configure: WARNING: Could not find a valid numpy installation, disabling.
	checking whether arm-oe-linux-gnueabi-gcc -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -mno-thumb understands -Wall... yes
	checking whether arm-oe-linux-gnueabi-gcc -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -mno-thumb understands -fno-strict-aliasing... yes
	checking whether arm-oe-linux-gnueabi-gcc -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -mno-thumb understands -std=c9x... yes
	configure: error: conditional "HAVE_GTK_2_16" was never defined.
	Usually this means the macro was only invoked conditionally.
	ERROR: Function do_configure failed

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Khem Raj <raj.khem@gmail.com>