supertux 0.1.3: depend on libmikmod(fix not-starting issue)
If we don't depend on libmikmod, and that we enable sound and/or music
supertux exits with an error message and doesn't start:
  root@nokia900 ~ # supertux
  Datadir: /usr/bin/../share/supertux
  Warning: No joysticks are available.

  Error: Couldn't load musicfile
  /usr/bin/../share/supertux/music/SALCON.MOD

  Aborted

PR was also bumped