native.bbclass: define empty PACKAGES_DYNAMIC
* suggested by kergoth on #oe as response to similar patch limited to gtk+
  http://lists.linuxtogo.org/pipermail/openembedded-devel/2011-March/031074.html
  15:03 < kergoth_> JaMa: pretty sure we just need PACKAGES_DYNAMIC = ""
  and PACKAGES_DYNAMIC_virtclass-native = "" in native.bbclass.
  everyone i've talked to so far as agreed that it's a sane approach,
  including RP.

* otherwise couple of errors like this are shown
  NOTE: multiple providers are available for runtime gdk-pixbuf-loader-gif (gtk+-native, gtk+, gtk+-fastscaling)
  NOTE: consider defining a PREFERRED_PROVIDER entry to match gdk-pixbuf-loader-gif
  ERROR: Trying to resolve runtime dependency gdk-pixbuf-loader-xpm resulted in conflicting PREFERRED_PROVIDER entries being found.
  The providers found were: ['/OE/dev/recipes/gtk+/gtk+_2.20.1.bb', 'virtual:native:/OE/dev/recipes/gtk+/gtk+_2.20.0.bb']
  The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_gtk+ = gtk+', 'PREFERRED_PROVIDER_gdk-pixbuf-csource-native = gtk+-native']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Acked-by: Otavio Salvador <otavio@ossystems.com.br>