Building fails with the following error.
| ./CXX -c ipstreams/wvunixdgsocket
| In file included from ./include/wvunixdgsocket.h:13:0,
|                  from ipstreams/wvunixdgsocket.cc:1:
| ./include/wvaddr.h: In member function 'uint32_t WvIPAddr::addr() const':
| ./include/wvaddr.h:284:31: warning: dereferencing type-punned pointer will break strict-aliasing rules
| ipstreams/wvunixdgsocket.cc: In constructor 'WvUnixDGSocket::WvUnixDGSocket(const WvFastString&, bool, int)':
| ipstreams/wvunixdgsocket.cc:50:32: error: 'chmod' was not declared in this scope
| make: *** [ipstreams/wvunixdgsocket.o] Error 1

This patch is build tested using `angstrom-2010.x` and `minimal` for `MACHINE = "beagleboard"`. The build still fails when uClibc is used.

Signed-off-by: Søren Holm <sgh@sgh.dk>
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Khem Raj <raj.khem@gmail.com>