cairo: depend on glib-2.0 to fix compile error
| In file included from cairo-gobject-enums.c:8:0:
| cairo-gobject.h:44:25: fatal error: glib-object.h: No such file or directory

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Acked-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Frans Meulenbroeks <fransmeulenbroeks@gmail.com>