ezx/ezx-gpiotool_svn.bb: make the recipe build again
Pass ${LDFLAGS} in order to make the following error go away:
ERROR: QA Issue with ezx-gpiotool: No GNU_HASH in the elf binary

This is a workaround until the upstream Makefile is fixed properly.

While at it remove the unused do_stage() function.

Signed-off-by: Antonio Ospite <ospite@studenti.unina.it>