libqtaux2: fix staging of opie headers.
* staging code in do_compile has been converted and moved in do_install
* fix breakage introduced with febcae3b7b0b58c2668892ad1798eb1368bd4bc4
* (liquidset.cpp:38:32: error: opie2/ocolorbutton.h: No such file or dir...)
* tested rebuilding opie-image armv5te from scratch
* bump PR