linux-handhelds-2.6: fix compilation with gcc-4.3
Backport time.h patch from 2.6.25 kernel
(commit 38332cb98772f5ea757e6486bed7ed0381cb5f98)

It fixes following error during compilation:
  LD      .tmp_vmlinux1
kernel/built-in.o: In function `getnstimeofday':
utsname_sysctl.c:(.text+0xf110): undefined reference to `__aeabi_uldivmod'
kernel/built-in.o: In function `do_gettimeofday':
utsname_sysctl.c:(.text+0xf1d0): undefined reference to `__aeabi_uldivmod'
utsname_sysctl.c:(.text+0xf1ec): undefined reference to `__aeabi_uldivmod'
kernel/built-in.o: In function `do_timer':
utsname_sysctl.c:(.text+0x100ec): undefined reference to `__aeabi_uldivmod'
utsname_sysctl.c:(.text+0x1010c): undefined reference to `__aeabi_uldivmod'
make: *** [.tmp_vmlinux1] Error 1

See also similar OE bug #4333

Signed-off-by: Dmitry Artamonow <mad_soft@inbox.ru>
Signed-off-by: Koen Kooi <koen@openembedded.org>