libgles-omap3: fix 3 build issues with external CSL toolchain
Fix the following 3 build issues:

1. X11ROOT is used by GFX SDK Makefiles as a root of X11 installation and
results in -I$(X11ROOT)/include and -L$(X11ROOT)/lib in CFLAGS/LDFLAGS.
Set it to ${STAGING_DIR_HOST}/usr instead of ${STAGING_INCDIR}. Otherwise
the build fails with the following error messages:
PVRShellOS.h:18:22: error: X11/Xlib.h: No such file or directory
PVRShellOS.h:19:23: error: X11/Xutil.h: No such file or directory

2. Set TOOLCHAIN variable used in GFX SDK Makefiles to point to the toolchain
location. Fixes the following message, among others:
ld: warning: library search path "/lib" is unsafe for cross-compilation

3. Add libXdmcp to the list of linked X11 libraries, in addition to libX11
and libXau. Link stage failure:
ld: warning: libXdmcp.so.6, needed by libX11.so, not found
libX11.so: undefined reference to `XdmcpWrap'

Signed-off-by: Denys Dmytriyenko <denis@denix.org>