linux-bug: fix undefined reference to `__gnu_mcount_nc' issue and bump PR
Without that fix we have:
    LD      .tmp_vmlinux1
  init/built-in.o: In function `run_init_process':
  calibrate.c:(.text+0x10): undefined reference to `__gnu_mcount_nc'
  init/built-in.o: In function `init_post':
  calibrate.c:(.text+0x3c): undefined reference to `__gnu_mcount_nc'
  init/built-in.o: In function `do_one_initcall':
  calibrate.c:(.text+0x148): undefined reference to `__gnu_mcount_nc'
  init/built-in.o: In function `name_to_dev_t':
  calibrate.c:(.text+0x2cc): undefined reference to `__gnu_mcount_nc'
  init/built-in.o: In function `set_reset_devices':
  calibrate.c:(.init.text+0x10): undefined reference to `__gnu_mcount_nc'
  init/built-in.o:calibrate.c:(.init.text+0x38): more undefined references to `__gnu_mcount_nc' follow
  make: *** [.tmp_vmlinux1] Error 1
  FATAL: oe_runmake failed

Thanks khem in #oe on Freenode on irc for help:
  Feb 14 19:21:26 <khem>  GNUtoo|laptop: are you using profiling
  [...]
  Feb 14 19:57:13 <khem>  GNUtoo|laptop: ok so here it your problem you are passing -pg
  Feb 14 19:57:16 <khem>  to compiler
  [...]
  Feb 14 19:58:11 <khem>  GNUtoo|laptop: thats only useful if you will provide mcount and other profiling hook implementation
  Feb 14 19:58:16 <khem>  compiler sort of expects it

  The solution I chose was to disable the CONFIG_FTRACE that added -pg (profiling compiler option)

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>