xoscope_1.12.bb: Fix build failure when comedilib has already been staged.
If comedilib is already staged, xoscope tries to use it and fails to build.

mipsel-oe-linux-gcc -march=mips32 -DHAVE_CONFIG_H -I. -I.. -I/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/include/gtk-1.2 -I/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/include/glib-1.2 -I/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/lib/glib/include  -isystem/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/include  -isystem/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -Os -Wall -MT callbacks.o -MD -MP -MF .deps/callbacks.Tpo -c -o callbacks.o callbacks.c
callbacks.c:29:19: error: static declaration of 'window' follows non-static declaration
callbacks.h:3:19: note: previous declaration of 'window' was here
make[2]: *** [callbacks.o] Error 1
make[2]: Leaving directory `/mnt/oe/tmp/work/mipsel-oe-linux/xoscope-1.12-r1/xoscope-1.12/comedi-glade-src'

So disable comedilib support at configure time. I assume since comedi is new
to the tree this year and xoscope was added years ago, that comedi support
is not desired.

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>