enjoy: Fix commit 1265ac and append to `DEPENDS`.
With commit 1265ac »enjoy_svn.bb: add missing DEPENDS for the needed gst-plugins« [1] previous `DEPENDS` assignment was discarded and task `configure` failed with the following error.

        checking pkg-config is at least version 0.9.0... yes
        checking for EDBUS... configure: error: Package requirements (edbus) were not met:

        No package 'edbus' found

        Consider adjusting the PKG_CONFIG_PATH environment variable if you
        installed software in a non-standard prefix.

        Alternatively, you may set the environment variables EDBUS_CFLAGS
        and EDBUS_LIBS to avoid the need to call pkg-config.
        See the pkg-config man page for more details.

        ERROR: Function do_configure failed

This patch fixes the error above and is tested using the following configurations.

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "2bd4f33"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-gnueabi"
        MACHINE           = "beagleboard"
        DISTRO            = "angstrom"
        DISTRO_VERSION    = "next"
        TARGET_FPU        = "hard"

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "fa3f861"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-gnueabi"
        MACHINE           = "beagleboard"
        DISTRO            = "minimal"
        DISTRO_VERSION    = "dev-snapshot-20101206"
        TARGET_FPU        = "hard"

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=1265ac068aa9f5bf0d8fee2cfbf8a1492cabe5a3

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>