libgsf: fix compile error, add missing dependency on gtk+
This patch fixes this compile error:
main.c:38:35: error: gdk-pixbuf/gdk-pixbuf.h: No such file or directory

Signed-off-by: Petr Štetiar <ynezz@true.cz>