enjoy: add `elementary` to `DEPENDS`
Task `configure` fails with the following error message.

	| checking pkg-config is at least version 0.9.0... yes
	| checking for EDBUS... yes
	| checking for ELEMENTARY... configure: error: Package requirements (elementary ecore-file) were not met:
	|
	| No package 'elementary' found
	|
	| Consider adjusting the PKG_CONFIG_PATH environment variable if you
	| installed software in a non-standard prefix.
	|
	| Alternatively, you may set the environment variables ELEMENTARY_CFLAGS
	| and ELEMENTARY_LIBS to avoid the need to call pkg-config.
	| See the pkg-config man page for more details.
	|
	| ERROR: Function do_configure failed
	NOTE: package enjoy-0.0+svnr55157-r2: task do_configure: Failed
	ERROR: TaskFailed event exception, aborting
	ERROR: Build of /oe/openembedded/recipes/e17/enjoy_svn.bb do_configure failed
	ERROR: Task 12 (/oe/openembedded/recipes/e17/enjoy_svn.bb, do_configure) failed with 256
	ERROR: '/oe/openembedded/recipes/e17/enjoy_svn.bb' failed
	ERROR: '/oe/openembedded/recipes/e17/enjoy_svn.bb' failed
	ERROR: '/oe/openembedded/recipes/e17/enjoy_svn.bb' failed

Adding `elementary` to `DEPENDS` fixes this problem and is tested with the following configurations.

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "2bd4f33"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-gnueabi"
        MACHINE           = "beagleboard"
        DISTRO            = "angstrom"
        DISTRO_VERSION    = "next"
        TARGET_FPU        = "hard"

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "fa3f861"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-gnueabi"
        MACHINE           = "beagleboard"
        DISTRO            = "minimal"
        DISTRO_VERSION    = "dev-snapshot-20101206"
        TARGET_FPU        = "hard"

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>