udev 165: depends on mtd-utils to fix compilation
Without that fix we have:
    CC     udev/udev-event.o
  In file included from extras/mtd_probe/mtd_probe.c:19:0:
  extras/mtd_probe/mtd_probe.h:20:26: fatal error: mtd/mtd-user.h: No such file or directory
  compilation terminated.

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>
Acked-by: Stefan Schmidt <stefan@buglabs.net>