mtools: fix 3.9.11 recipe to properly compile
Compilation was failing due a wrong command line param being passed to
GCC. This patch fixes it.

,----[ Failure ]
| cc1: error: unrecognized command line option "-m486"
`----

Besides the compilation error, mtools.patch is not necessary anymore
and not applicable to this version, thus droped.