libcap, libcap2: use automatic packaging to fix QA errors
Since commit 6883f6 [1] packages have been populated manually.

	FILES_${PN} = "${libdir}"
	FILES_${PN}-dev = "${includedir}"

This gives the following QA errors for `libcap` and `libcap2` (which is based on `libcap` [2]) [3].

• `libcap`:

	ERROR: QA Issue with libcap: non -dev package contains symlink .so: libcap path '/work/armv7a-oe-linux-uclibceabi/libcap-1.10-r2/packages-split/libcap/usr/lib/libcap.so'
	ERROR: QA Issue with libcap: non -dev package contains symlink .so: libcap path '/work/armv7a-oe-linux-uclibceabi/libcap-1.10-r2/packages-split/libcap/usr/lib/libcap.so'

• `libcap2`:

	ERROR: QA Issue with libcap2: non -dev package contains symlink .so: libcap2 path '/work/armv7a-oe-linux-uclibceabi/libcap2-2.16-r1/packages-split/libcap2/usr/lib/libcap.so'
	ERROR: QA Issue with libcap2: non -dev package contains symlink .so: libcap2 path '/work/armv7a-oe-linux-uclibceabi/libcap2-2.16-r1/packages-split/libcap2/usr/lib/libcap.so'

Using automatic packages the symlink `libcap.so -> libcap.so.1.10` is put into `libcap{,2}-dev`.

Note: The symlink `libcap.so.1 -> libcap.so.1.10` is still put into `libcap1_1.10-r2_armv7a.ipk` but does not raise a QA error.

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=6883f65588c6aa7e9780ff7c11b15a397382a422
[2] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=c71a6ebf796df907ba0d4339e6acf66faa3c6232
[3] http://lists.linuxtogo.org/pipermail/openembedded-devel/2011-January/028557.html

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
CC: Rolf Leggewie <no2spam@nospam.arcornews.de>
Acked-by: Dirk Opfer <dirk@do13.de>
Acked-by: Dirk Opfer <dirk@do13.de>
Signed-off-by: Khem Raj <raj.khem@gmail.com>