empathy 2.28.2: added libunique dependency to make it configure(now: compilation failure)
Here's the error log:
| checking for EMPATHY... configure: error: Package requirements (
|    glib-2.0 >= 2.16.0
|    gobject-2.0
|    gio-2.0 >= 2.16.0
|    gdk-x11-2.0
|    gtk+-2.0 >= 2.16.0
|    libebook-1.2
|    dbus-glib-1
|    telepathy-glib >= 0.7.35
|    telepathy-farsight
|    farsight2-0.10
|    gstreamer-0.10
|    unique-1.0
|    gnome-keyring-1 >= 2.22
| ) were not met:
|
| No package 'unique-1.0' found

While doing the change I broke the long dependency line in smaller parts with \

Now it fails to compile like this:
cc1: warnings being treated as errors
uniquebackend-bacon.c: In function 'unique_backend_bacon_get_type':
/home/embedded/oetmp_openmoko/staging/armv4t-oe-linux-gnueabi/usr/include/glib-2.0/glib/gthread.h:344: error: dereferencing pointer 'value_location.1' does break strict-aliasing rules
/home/embedded/oetmp_openmoko/staging/armv4t-oe-linux-gnueabi/usr/include/glib-2.0/glib/gthread.h:344: note: initialized from here
make[4]: *** [libunique_bacon_la-uniquebackend-bacon.lo] Error 1