Merge nslu2-linux@nslu2-linux.bkbits.net:openembedded into giantshoulder.com:/home/tom/dev/openslug/openembedded
2005/03/21 06:41:26-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 15:00:24+01:00 handhelds.org!CoreDump
Update netbase from 4.19 to 4.20 since 4.19 vanished upstream

2005/03/21 05:41:23-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 13:35:17+00:00 rpsys.net!RP
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into tim.rpsys.net:/usr/oe/openembedded

2005/03/21 13:34:55+00:00 rpsys.net!RP
openzaurus-2.6: Compile fixes from Dirk for tosa

2005/03/21 04:41:24-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 13:05:52+01:00 utwente.nl!koen
kbdd_cvs.bb: Apply patch from Paul Eggleton

2005/03/21 03:41:22-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 12:41:15+01:00 utwente.nl!koen
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into bitbake.utwente.nl:/home/koen/OE/openembedded

2005/03/21 12:40:56+01:00 utwente.nl!koen
matchbox-themes-extra_0.3.bb: hh.org -> o-hand.com

2005/03/21 12:27:55+01:00 uni-frankfurt.de!mickeyl
update updater.sh for c3000

2005/03/21 21:50:32+10:30 (none)!rwhitby
Unslung 4.6-alpha

2005/03/21 12:19:50+01:00 uni-frankfurt.de!mickeyl
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into r2d2.tm.informatik.uni-frankfurt.de:/local/pkg/oe/packages

2005/03/21 12:19:34+01:00 uni-frankfurt.de!mickeyl
upgrade cumulus to 1.2.1 and lower the default preference of the cvs version

2005/03/21 21:45:32+10:30 (none)!rwhitby
Fixed unslung-packages

2005/03/21 21:37:40+10:30 (none)!rwhitby
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into home.(none):/home/bitbake/openembedded

2005/03/21 21:36:04+10:30 (none)!rwhitby
Updated unsling script to support external rootfs in Unslung distro

2005/03/21 10:57:51+00:00 rpsys.net!RP
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into tim.rpsys.net:/usr/oe/openembedded

2005/03/21 10:57:29+00:00 rpsys.net!RP
linux-hotplug: Update mmc.agent to work with 2.6 kernels + udev

2005/03/21 02:41:25-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 11:23:54+01:00 utwente.nl!koen
xcursor-transparent-theme_0.1.1.bb:
  hh.org -> o-hand.com

2005/03/21 01:41:23-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 20:33:14+10:30 (none)!rwhitby
Added DISTRO_TYPE to Unslung and OpenSlug

2005/03/21 10:47:07+01:00 utwente.nl!koen
task-bootstrap.bb:
  use base-passwd-3.5.9

2005/03/21 10:23:06+01:00 handhelds.org!CoreDump
Fix PR...

2005/03/21 10:21:57+01:00 handhelds.org!CoreDump
Upgrade base-passwd from 3.5.7 to 3.5.9 as 3.5.7 is no longer available from upstream

2005/03/20 23:03:22-10:00 (none)!dyoung
device_table-unslung.txt:
  Add /dev/video0

2005/03/20 22:51:31-10:00 (none)!dyoung
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into builder.(none):/home/dereky/bbroot/openembedded

2005/03/20 22:50:35-10:00 (none)!dyoung
Oops forgot to enable the camera device

2005/03/21 00:41:23-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/20 22:37:46-10:00 (none)!dyoung
defconfig:
  Enable video_dev=m and bring config up to post-config standard.

2005/03/21 09:15:32+01:00 mn-solutions.de!schurig
openswan: download URL fix from Gints Polis

2005/03/21 09:13:51+01:00 mn-solutions.de!schurig
Qt/E 2.3.10:
Changed ramses-keyboard.patch from patch to copy-a-file mode. It happend one time
too often that someone else broke my patch.

2005/03/20 16:23:39-10:00 (none)!dyoung
Update the version to spca5xx camera driver

2005/03/20 16:41:28-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 00:25:15+00:00 rpsys.net!RP
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into tim.rpsys.net:/usr/oe/openembedded

2005/03/21 00:24:56+00:00 rpsys.net!RP
openzaurus-2.6: Fix the mtd mapped PROM driver so it works and add definitions for tosa/spitz to it (patch commited to MTD CVS).

2005/03/20 13:52:55-10:00 (none)!dyoung
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into builder.(none):/home/dereky/bbroot/openembedded

2005/03/20 13:51:25-10:00 (none)!dyoung
renamed a file to reflect version

2005/03/20 15:41:24-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/21 00:26:12+01:00 uni-frankfurt.de!mickeyl
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into r2d2.tm.informatik.uni-frankfurt.de:/local/pkg/oe/packages

2005/03/21 00:26:02+01:00 uni-frankfurt.de!mickeyl
add libsndfile and add polypaudio. the latter in nonworking, because of a bogus 'undefined reference to pa_client_conf_from_x11'

2005/03/21 00:17:43+01:00 handhelds.org!zecke
QtEmbedded iPAQ sound:
	-Hardcode to use stereo
	-Do not crash on empty sound files

2005/03/20 12:41:29-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/20 21:34:03+01:00 uni-frankfurt.de!mickeyl
update qpegps 0.9.2.3 and remove 0.9.1+cvs

2005/03/20 10:41:22-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/20 18:30:33+00:00 rpsys.net!RP
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into tim.rpsys.net:/usr/oe/openembedded

2005/03/20 18:29:30+00:00 rpsys.net!RP
openzaurus-2.6: Fix corrupted patch

2005/03/20 19:15:02+01:00 uni-frankfurt.de!mickeyl
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into gandalf.tm.informatik.uni-frankfurt.de:/local/pkg/oe/packages

2005/03/20 19:14:15+01:00 uni-frankfurt.de!mickeyl
add meta task for all python packages compatible w/ sharprom

2005/03/20 09:41:22-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/20 17:22:01+00:00 rpsys.net!RP
openzaurus-2.6: bump PR

2005/03/20 17:18:43+00:00 rpsys.net!RP
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into tim.rpsys.net:/usr/oe/openembedded

2005/03/20 17:18:21+00:00 rpsys.net!RP
openzaurus-2.6: Add pxa turbo mode suspend/resume fix, final updates for multi platform w100fb, patch tweaks to keep compatible with mainline.

2005/03/20 04:19:47-10:00 (none)!dyoung
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into builder.(none):/home/dereky/bbroot/openembedded

2005/03/21 01:08:40+10:30 (none)!rwhitby
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into home.(none):/home/bitbake/openembedded

2005/03/21 01:08:20+10:30 (none)!rwhitby
Merged unslung-standard and unslung-able into a single unslung distro.  Updated to support downloadable kernel modules.

2005/03/20 04:10:03-10:00 (none)!dyoung
w3cam is a lightweight application to grab images from a V4L device

2005/03/20 01:41:29-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/20 10:04:55+01:00 uni-frankfurt.de!mickeyl
opie-datebook-plugins: fix APPNAME and remove errornous install. guys, we don't install binaries by hand for Opie packages. Opie.bbclass exists for a reason - read it\!

2005/03/20 19:22:11+10:30 (none)!rwhitby
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into home.(none):/home/wl500g/openembedded

2005/03/19 12:41:23-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/19 20:50:29+01:00 uni-frankfurt.de!mickeyl
add sets module to python-math

2005/03/19 10:41:24-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/19 19:22:37+01:00 uni-frankfurt.de!mickeyl
zaurus kernels: catch up with package renaming

2005/03/19 19:16:02+01:00 uni-frankfurt.de!mickeyl
bump CVSDATE for openzaurus-3.5.3

2005/03/19 19:00:53+01:00 uni-frankfurt.de!mickeyl
only apply allow-no-pw patch to dropbear if DISTRO_TYPE == debug

2005/03/19 08:41:26-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/19 16:31:50+00:00 reciva.com!pb
set gpe-contacts 0.36 as preferred version

2005/03/19 16:30:54+00:00 reciva.com!pb
update gpe-contacts to 0.36


2005/03/19 07:41:23-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/19 16:34:57+01:00 utwente.nl!koen
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into bitbake.utwente.nl:/home/koen/OE/openembedded

2005/03/19 16:34:45+01:00 utwente.nl!koen
familiar-0.8.2.conf:
  don't set cvsdate for now

2005/03/19 15:46:52+01:00 vanille.de!mickeyl
this changeset fixes the broken keyboard autorepeat for ipaq and sl5xxx

2005/03/19 04:41:29-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/19 12:38:25+01:00 utwente.nl!koen
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into bitbake.utwente.nl:/home/koen/OE/openembedded

2005/03/19 12:38:07+01:00 utwente.nl!koen
familiar-0.8.2.conf:
  move CVSDATE to tuesday

2005/03/19 18:19:59+10:30 (none)!rwhitby
Added muxsshssl and nail

2005/03/18 14:41:35-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/19 08:49:24+10:30 (none)!rwhitby
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into home.(none):/home/bitbake/openembedded

2005/03/19 08:48:48+10:30 (none)!rwhitby
Fixed muxsshssl unpacking

2005/03/18 22:59:51+01:00 zeckescompany.nl!alwin
added datebookplugins to build-system

2005/03/18 12:41:25-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 15:40:19-05:00 handhelds.org!kergoth
Fix the permissions on /dev/tty and /dev/console in the /dev/ makedevs'd ramdisk.  This fixes that annoying bug where | more doesnt work, and also makes the openssh ssh client stop sucking.

2005/03/18 11:41:27-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 14:01:26-05:00 handhelds.org!kergoth
Fix ttyconv's DESCRIPTION.

2005/03/18 14:00:35-05:00 handhelds.org!kergoth
Merge oe-devel@oe-devel.bkbits.net:openembedded
into handhelds.org:/home/kergoth/code/openembedded

2005/03/18 14:00:11-05:00 handhelds.org!kergoth
Add ttyconv 0.2.3 (A small app to convert terminal sessions from one encoding to another).

2005/03/18 19:58:03+01:00 dyndns.org!reenoo
Merge oe-devel@oe-devel.bkbits.net:openembedded
into sugarcube.dyndns.org:/home2/oe/bakery/openembedded

2005/03/18 19:55:40+01:00 dyndns.org!reenoo
kaffe: resurrect kaffe from nonworking. the packaging still needs some polishing. the -qt incarnation needs to be tested and the (qt only) stuff from nonworking removed if it works.

2005/03/18 10:42:21-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 13:04:34-05:00 handhelds.org!kergoth
Add 'patch' to the RDEPENDS of bazaar.  It works now, if you install GNU's tar instead of busybox's.

2005/03/18 09:42:15-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 12:19:48-05:00 handhelds.org!kergoth
Merge oe-devel@oe-devel.bkbits.net:openembedded
into handhelds.org:/home/kergoth/code/openembedded

2005/03/18 12:19:12-05:00 handhelds.org!kergoth
Add ccache.inc, which:
	Makes ccache use a TMPDIR specific ccache directory if using the crosscompiler,
	since it isn't likely to be useful with any other toolchain than the one we just
	built, and would otherwise push more useful things out of the default cache.

2005/03/18 08:41:34-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 17:19:59+01:00 local!hrw
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded/
into marcinj.local:/home/hrw/zaurus/bb/openembedded

2005/03/18 10:34:22-05:00 handhelds.org!kergoth
Make the bazaar .bb install its bazaar-gpg-check awk script, and RSUGGESTS gnupg.

2005/03/18 10:16:16-05:00 handhelds.org!kergoth
neon: fix LICENSE.  Bump PR.  Pass --enable-shared --enable-static.  Add a do_stage.

2005/03/18 10:10:45-05:00 handhelds.org!kergoth
Merge oe-devel@oe-devel.bkbits.net:openembedded
into handhelds.org:/home/kergoth/code/openembedded

2005/03/18 10:10:26-05:00 handhelds.org!kergoth
Add bazaar 1.2 (an implementation of GNU Arch in C, based on tla).

2005/03/18 06:41:26-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 15:07:27+01:00 local!hrw
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded/
into marcinj.local:/home/hrw/zaurus/bb/openembedded

2005/03/18 15:07:05+01:00 local!hrw
added more fonts to meta-opie

2005/03/18 13:43:33+00:00 rpsys.net!RP
openzaurus-2.6: Dirks updates to Tosa and some w100fb updates

2005/03/18 04:41:25-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 22:57:59+10:30 (none)!rwhitby
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into home.(none):/home/bitbake/openembedded

2005/03/18 22:57:42+10:30 (none)!rwhitby
Added muxsshssl, but still waiting for sf.net CVS to update before it can be used.

2005/03/18 13:23:12+01:00 uni-frankfurt.de!mickeyl
ship opie-qss in the default image

2005/03/18 03:41:21-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 12:25:50+01:00 local!hrw
added development version 2.0.17 of kdepimpi (marked as non-default)

2005/03/18 21:55:18+10:30 (none)!rwhitby
Added mt-daapd, strace and nail to openslug-packages.

2005/03/18 01:04:24-10:00 (none)!dyoung
A enhanced mailx replacement

2005/03/18 00:46:33-10:00 (none)!dyoung
mt-daapd_0.2.1.1.bb:
  changed the dl location

2005/03/18 20:59:08+10:30 (none)!rwhitby
Merge bk://nslu2-linux@nslu2-linux.bkbits.net/openembedded
into home.(none):/home/bitbake/openembedded

2005/03/18 20:58:31+10:30 (none)!rwhitby
Added sudo and perl to openslug-packages, and demoted mt-daapd

2005/03/17 19:41:54-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/17 22:30:43-05:00 handhelds.org!kergoth
Kill a few files that were unintentionally checked in, in the last cset.

2005/03/17 22:26:35-05:00 handhelds.org!kergoth
Merge oe-devel@oe-devel.bkbits.net:openembedded
into handhelds.org:/home/kergoth/code/openembedded

2005/03/17 22:26:19-05:00 handhelds.org!kergoth
Start adding wrt54g{,s} bits.  This is the linux-wrt 2.4.20 kernel, and an /etc/network/interfaces file.

2005/03/17 16:42:09-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/18 00:45:28+01:00 handhelds.org!zecke
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into handhelds.org:/home/ich/programming/oe/openembedded

2005/03/18 00:44:27+01:00 handhelds.org!zecke
ZeeCookBook patch by Philip Frampton:
	-Update Zeecookbook to 1.1 from 1.0beta3
	-Fix packaging


2005/03/17 15:41:32-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/17 18:37:37-05:00 handhelds.org!kergoth
Merge oe-devel@oe-devel.bkbits.net:openembedded
into handhelds.org:/home/kergoth/code/openembedded

2005/03/17 18:37:17-05:00 handhelds.org!kergoth
Add pcmciautils 001 (can use these to manage 16 bit pcmcia cards with hotplug, given a recent enough kernel and sysfsutils).

2005/03/17 18:35:58-05:00 handhelds.org!kergoth
Apply libsysfs write attributes patch to sysfsutils (required for pcmciautils).

2005/03/18 00:06:08+01:00 utwente.nl!koen
meta-sectest-gpe.bb:  disable btscanner and dillo for now

2005/03/17 14:41:19-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/17 23:37:28+01:00 utwente.nl!koen
Merge bk://oe-devel@oe-devel.bkbits.net/openembedded
into bitbake.utwente.nl:/home/koen/OE/openembedded

2005/03/17 23:37:14+01:00 utwente.nl!koen
mbmerlin_0.8.1-2.bb:
  unbork mbmerlin

2005/03/17 22:43:32+01:00 handhelds.org!zecke
Pocket Cellar patches courtsey Philip Frampton:
	-Patches are not yet 100% Qtopia/Opie conform but still it is an improvement
	-Lookup the PocketCellar Wine Database at the right directory

2005/03/17 21:03:50+01:00 dyndns.org!reenoo
vlc-gpe: remove unnecessary "/" separator one more time.

2005/03/17 06:41:26-08:00 bkbits.net!nslu2-linux.adm
Merge bk://oe-devel.bkbits.net/openembedded
into bkbits.net:/repos/n/nslu2-linux/openembedded

2005/03/17 14:56:19+01:00 utwente.nl!koen
preferred-gpe-versions.inc:
  newer xextensions

2005/03/16 09:40:06+10:30 (none)!rwhitby
Patch for ipkg which makes it respect the setting of sysconfdir.

2005/03/16 09:39:14+10:30 (none)!rwhitby
Added wl500g machine and AsusOE distro

2005/03/16 08:08:59+10:30 (none)!rwhitby
Merge bk://oe-devel.bkbits.net/openembedded
into home.(none):/home/wl500g/openembedded

2005/03/11 22:36:27+10:30 (none)!rwhitby
Merge bk://oe-devel.bkbits.net/openembedded
into home.(none):/home/wl500g/openembedded

BKrev: 423ee345bbZEjSmlBpykWs0rnfomxA