Revert "libinih: add"
This reverts commit 92f66ee0a4e0958bfabc10cc2c2e8a211e8e31f3.

This recipe gives a parsing error

ERROR: Error parsing /home/frans/oe/openembedded/recipes/libinih/libinih_git.bb: Fetch command export HOME="/home/frans"; export SSH_AUTH_SOCK="/tmp/ssh-CCruJ2497/agent.2497"; export
PATH="/home/frans/oe/openembedded/conf/bin:/home/frans/oe/openembedded/bin:/home/frans/oe/myopenembedded/conf/bin:/home/frans/oe/myopenembedded/bin:/home/frans/oe/tmp_minimal/sysroots/i686-linux/usr/ppce500v2/bin:/home/frans/oe/tmp_minimal/sysroots/i686-linux/usr/sbin:/home/frans/oe/tmp_minimal/sysroots/i686-linux/usr/bin:/home/frans/oe/tmp_minimal/sysroots/i686-linux/sbin:/home/frans/oe/tmp_minimal/sysroots/i686-linux//bin:/home/frans/oe/bitbake/bin:/home/frans/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/lib/qt3/bin:/home/frans/bin:.";
git ls-remote git://projetos.ossystems.com.br/git/libinih.git master failed with signal 128, output:
fatal: read error: Connection reset by peer

also SRCREV = AUTOREV is less desirable