nfs-utils: add patch for missing include sys/stat.h
* without, it fails with undefined reference to S_ISREG (the same for S_ISDIR)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>