lightmediascanner: Add `virtual/libiconv` to `DEPENDS` and add patch for `libiconv`
Task compile fails with the following error using `minimal-uclibc` for `MACHINE = "beagleboard"`.

        Making all in bin
        make[3]: Entering directory `/oe/build-minimal-uclibc/minimal-uclibc-dev/work/armv7a-oe-linux-uclibceabi/lightmediascanner-1_0.4.1.0-r2/lightmediascanner-0.4.1.0/src/bin'
          CC     test.o
          CC     list-parsers.o
          CCLD   list-parsers
          CCLD   test
        ../../src/lib/.libs/liblightmediascanner.so: undefined reference to `libiconv_open'
        ../../src/lib/.libs/liblightmediascanner.so: undefined reference to `libiconv_close'
        ../../src/lib/.libs/liblightmediascanner.so: undefined reference to `libiconv'
        collect2: ld returned 1 exit status
        make[3]: *** [list-parsers] Error 1
        make[3]: *** Waiting for unfinished jobs....
        ../../src/lib/.libs/liblightmediascanner.so: undefined reference to `libiconv_open'
        ../../src/lib/.libs/liblightmediascanner.so: undefined reference to `libiconv_close'
        ../../src/lib/.libs/liblightmediascanner.so: undefined reference to `libiconv'
        collect2: ld returned 1 exit status
        make[3]: *** [test] Error 1

1. The libiconv Web site [1] tells to add `@LTLIBICONV@` to the linke command lines of the libraries or executables using libiconv functions. Gustavo send me a patch implementing this.

2. `touch config.rpath` before task configure because of the following error.

        autoreconf: running: automake --foreign --add-missing --copy --force-missing --warnings=cross
        automake: unknown warning category `cross'
        configure.ac:37: required file `./config.rpath' not found
        autoreconf: automake failed with exit status: 1

3. The next thing is to add `virtual/libiconv` to `DEPENDS`. EGLIBC and glibc do give an error because they include iconv support(?).

          CC     lightmediascanner_utils.lo
          CC     lightmediascanner.lo
          CC     lightmediascanner_charset_conv.lo
          CC     lightmediascanner_process.lo
        lightmediascanner_charset_conv.c:22:19: fatal error: iconv.h: No such file or directory
        compilation terminated.

This patch is build tested using `angstrom-2010.x` and `minimal{,-uclibc}` for `MACHINE = "beagleboard"`. Additionally `enjoy_svn.bb` depending on `lightmediascanner` has been build tested too.

[1] http://www.gnu.org/software/libiconv/

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>