tslib-git: update to git master
* 5243db505b109df3001f doesn't exist so fetch is failing.
error: pathspec '5243db505b109df3001f' did not match any file(s) known to git.

Signed-off-by: Eric Bénard <eric@eukrea.com>
Acked-by: Khem Raj <raj.khem@gmail.com>