lua, lua-gtk2: move to obsolete.
Lua fails to build. There are newer recipes (lua5.1) in tree, only
lua-gtk2 uses this old recipe and nothing uses lua-gtk2.

mipsel-oe-linux-gcc -march=mips32 -o ../../bin/luac -L/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/lib -Wl,-rpath-link,/mnt/oe/tmp/sysroots/mipsel-oe-linux/usr/lib -Wl,-O1  -Wl,-E luac.o print.o lopcodes.o -L../../lib -llua -llualib -lm -ldl -lreadline
luac.o: In function `strip':
luac.c:(.text+0xa8): undefined reference to `luaM_realloc'
luac.c:(.text+0xc4): undefined reference to `luaM_realloc'
luac.c:(.text+0xdc): undefined reference to `luaM_realloc'
luac.o: In function `main':
luac.c:(.text+0x3f8): undefined reference to `lua_open'
luac.c:(.text+0x438): undefined reference to `lua_tostring'
luac.c:(.text+0x4cc): undefined reference to `luaM_realloc'
luac.c:(.text+0x4f4): undefined reference to `luaM_realloc'
collect2: ld returned 1 exit status
make[1]: *** [../../bin/luac] Error 1

Signed-off-by: Graham Gower <graham.gower@gmail.com>
Acked-by: Frans Meulenbroeks <fransmeulenbroeks@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>