starling: change `gst-plugin-ivorbis` to `gst-plugin-ivorbisdec` in `RRECOMMENDS_${PN}`
With commit e6d170ab [1]

        commit e6d170abad28fcd0e3b8ba831705bed23e3309a4
        Author: Martin Jansa <martin.jansa@gmail.com>
        Date:   Thu Apr 7 00:12:22 2011 +0000

            gst-plugins: define disjunctive PACKAGES_DYNAMIC for each pack base/good/bad/ugly

`bitbake starling` fails with the following error message.

        ERROR: Nothing RPROVIDES 'gst-plugin-ivorbis' (but /oe/openembedded/recipes/starling/starling_0.9.bb

The GStreamer recipe creates only a plugin named `gst-plugin-ivorbisdec` which is the same as `gst-plugin-ivorbis`.

        gst-plugins-base-0.10.32$ ./configure --help
        […]
          --disable-ivorbis            disable integer vorbis plug-in: ivorbisdec
        […]

This patch is tested using the following configuration.

        Build Configuration:
        BB_VERSION        = "1.12.0"
        METADATA_BRANCH   = "master"
        METADATA_REVISION = "0779626"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-uclibceabi"
        MACHINE           = "beagleboard"
        DISTRO            = "minimal-uclibc"
        DISTRO_VERSION    = "dev-snapshot-20110413"
        TARGET_FPU        = "hard"

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=e6d170abad28fcd0e3b8ba831705bed23e3309a4

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Martin Jansa <Martin.Jansa@gmail.com>