gypsy: add `bluez4` to `DEPENDS` instead of `bluez-libs`
Task `configure` when running `bitbake gypsy` failed with the following error.

        checking pkg-config is at least version 0.9.0... yes
        checking for GYPSY... configure: error: Package requirements (glib-2.0 dbus-glib-1 >= 0.60 bluez) were not met:

        No package 'bluez' found

        Consider adjusting the PKG_CONFIG_PATH environment variable if you
        installed software in a non-standard prefix.

        Alternatively, you may set the environment variables GYPSY_CFLAGS
        and GYPSY_LIBS to avoid the need to call pkg-config.
        See the pkg-config man page for more details.

        ERROR: Function do_configure failed

`bluez4` is needed in the `DEPENDS` list instead of `bluez-libs`.

This patch is build tested with the following configurations.

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "a3f3bc0"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-uclibceabi"
        MACHINE           = "beagleboard"
        DISTRO            = "minimal-uclibc"
        DISTRO_VERSION    = "dev-snapshot-20101210"
        TARGET_FPU        = "hard"

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "a3f3bc0"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-gnueabi"
        MACHINE           = "beagleboard"
        DISTRO            = "minimal"
        DISTRO_VERSION    = "dev-snapshot-20101210"
        TARGET_FPU        = "hard"

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Khem Raj <raj.khem@gmail.com>