watchdog_5.2.6: remove recipe since task fetch fails
Watchdog is not available anymore on [1] and neither the official location [2].

	$ bitbake -c fetch -b /oe/openembedded/recipes/watchdog/watchdog_5.2.6.bb
	[…]
	NOTE: Running task 2 of 2 (ID: 0, /oe/openembedded/recipes/watchdog/watchdog_5.2.6.bb, do_fetch)
	NOTE: package watchdog-5.2.6-r4: task do_fetch: Started
	--2011-04-10 00:09:07--  http://www.ibiblio.org/pub/Linux/system/daemons/watchdog/watchdog-5.2.6.tar.gz
	 Resolving www.ibiblio.org... 152.19.134.40
	 Connecting to www.ibiblio.org|152.19.134.40|:80... connected.
	 HTTP request sent, awaiting response... 404 Not Found
	 2011-04-10 00:09:07 ERROR 404: Not Found.

	 --2011-04-10 00:09:07--  http://mirrors.openembedded.org/watchdog-5.2.6.tar.gz
	 Resolving mirrors.openembedded.org... 82.197.159.157
	 Connecting to mirrors.openembedded.org|82.197.159.157|:80... failed: Connection refused.
	 --2011-04-10 00:09:07--  http://sources.openembedded.org/watchdog-5.2.6.tar.gz
	 Resolving sources.openembedded.org... 140.211.169.165
	 Connecting to sources.openembedded.org|140.211.169.165|:80... connected.
	 HTTP request sent, awaiting response... 404 Not Found
	 2011-04-10 00:09:08 ERROR 404: Not Found.

	NOTE: package watchdog-5.2.6-r4: task Fetch failed: Unable to fetch URL http://www.ibiblio.org/pub/Linux/system/daemons/watchdog/watchdog-5.2.6.tar.gz from any source.: Failed
	ERROR: Function 'Fetch failed: Unable to fetch URL http://www.ibiblio.org/pub/Linux/system/daemons/watchdog/watchdog-5.2.6.tar.gz from any source.' failed
	ERROR: Task 0 (/oe/openembedded/recipes/watchdog/watchdog_5.2.6.bb, do_fetch) failed with exit code '1'
	ERROR: '/oe/openembedded/recipes/watchdog/watchdog_5.2.6.bb' failed

Since this version is not pinned by anything just remove it.

[1] http://www.ibiblio.org/pub/Linux/system/daemons/watchdog/${P}.tar.gz
[2] http://sourceforge.net/projects/watchdog/files/watchdog/

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Eric Bénard <eric@eukrea.com>