vlc_1.1.4.1: add `lua5.1-native` to `DEPENDS` and `lua5.1` to `RDEPENDS`
Task `configure` failed with the following error.

        […]
        checking for LUA... yes
        checking for luac... no
        configure: error: Could not find the LUA byte compiler.
        ERROR: Function do_configure failed

It turns out that `luac` is needed on the build system and therefore `lua5.1-native` needs to be added to `DEPENDS`. Thanks to
Petr Štetiar for his advise on this issue [1].

With this patch applied I built this recipe successfully with the following build configuration.

        Build Configuration:
        BB_VERSION        = "1.10.0"
        METADATA_BRANCH   = "org.openembedded.dev"
        METADATA_REVISION = "28492a5"
        TARGET_ARCH       = "arm"
        TARGET_OS         = "linux-gnueabi"
        MACHINE           = "beagleboard"
        DISTRO            = "angstrom"
        DISTRO_VERSION    = "2010.7-test-20101106"
        TARGET_FPU        = "hard"

[1] http://lists.linuxtogo.org/pipermail/openembedded-devel/2010-November/026631.html

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Khem Raj <raj.khem@gmail.com>