python-2.6: python-xml depends on python-elementtree
* Fixes the following error:

  import xml.etree.cElementTree
  File "/usr/lib/python2.6/xml/etree/cElementTree.py", line 3, in <module>
  from _elementtree import *
  ImportError: No module named _elementtree

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Khem Raj <raj.khem@gmail.com>