libomxil-bellagio_{0.9.2.1, git}: add patch: remove `-Werror` from `CFLAGS` to fix build with GCC 4.5
Am Montag, den 17.01.2011, 12:45 +0100 schrieb Paul Menzel:
> Build tested with `angstrom-2008.1` for `MACHINE = "beagleboard"`. With `angstrom-2010.x` it fails with the following error.
>
>         arm-angstrom-linux-gnueabi-libtool: compile:  arm-angstrom-linux-gnueabi-gcc -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -mthumb-interwork -mno-thumb -DHAVE_CONFIG_H -I. -I../.. -isystem/oe/build-angstrom-next/angstrom-dev/sysroots/armv7a-angstrom-linux-gnueabi/usr/include -I../../include -I../../src -isystem/oe/build-angstrom-next/angstrom-dev/sysroots/armv7a-angstrom-linux-gnueabi/usr/include -fexpensive-optimizations -fomit-frame-pointer -frename-registers -O2 -ggdb2 -Wall -Werror -DCONFIG_DEBUG_LEVEL=0 -MT libomxbase_la-omx_base_component.lo -MD -MP -MF .deps/libomxbase_la-omx_base_component.Tpo -c omx_base_component.c  -fPIC -DPIC -o .libs/libomxbase_la-omx_base_component.o
>         cc1: warnings being treated as errors
>         omx_base_component.c: In function 'omx_base_component_GetParameter':
>         omx_base_component.c:991:3: error: case value '2130706435' not in enumerated type 'OMX_INDEXTYPE'
>         omx_base_component.c:918:3: error: case value '2130706436' not in enumerated type 'OMX_INDEXTYPE'
>         make[3]: *** [libomxbase_la-omx_base_component.lo] Error 1
>         make[3]: Leaving directory `/oe/build-angstrom-next/angstrom-dev/work/armv7a-angstrom-linux-gnueabi/libomxil-bellagio-0.9.2.1+gitr0+772f0eca88b242ffb5469e8e381c63ce1f7cd3e1-r7.0/git/src/base'

Upstream advised to remove `-Werror` and is looking into it [1]. OpenBricks is applying the same patch [2].

A similar patch would make 0.9.2 compile, but this one here does not apply there (`CFLAGS="${CFLAGS} -Werror"` instead of `CFLAGS="${CFLAGS} -Wall -Werror"`).

[1] http://sourceforge.net/mailarchive/message.php?msg_id=26911808
[2] http://hg.openbricks.org/openbricks/rev/4f4ed3a596f2

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Khem Raj <raj.khem@gmail.com>