recipes: fix LICENSE fields
* & in LICENSE breaks distribute_sources
  ERROR: Function 'SRC_DISTRIBUTECOMMAND' failed (see /OE/tmpdir-shr/work/armv4t-oe-linux-gnueabi/pixman-0.22.0-r5.0/temp/log.do_distribute_sources.17340 for further information)
  ERROR: Logfile of failure stored in: /OE/tmpdir-shr/work/armv4t-oe-linux-gnueabi/pixman-0.22.0-r5.0/temp/log.do_distribute_sources.17340
  Log data follows:
  | WARNING: LICENSE: 'PublicDomain & MIT & MIT-style'
  | WARNING: licenses: ['PublicDomain', '&', 'MIT', '&', 'MIT-style']
  | WARNING: license: PublicDomain
  | WARNING: license: &
  | ERROR: Function 'SRC_DISTRIBUTECOMMAND' failed (see /OE/tmpdir-shr/work/armv4t-oe-linux-gnueabi/pixman-0.22.0-r5.0/temp/log.do_distribute_sources.17340 for further information)
  | + cd /OE/tmpdir-shr/deploy/sources/PublicDomain/pixman
  | + SRC_DISTRIBUTECOMMAND
  | + test -e /OE/pixman-0.22.0.tar.gz.md5
  | + ln -sf /OE/pixman-0.22.0.tar.gz .
  | + /pixman
  | + cd /OE/tmpdir-shr/deploy/sources/
  | /OE/tmpdir-shr/work/armv4t-oe-linux-gnueabi/pixman-0.22.0-r5.0/temp/run.SRC_DISTRIBUTECOMMAND.17340: line 95: /pixman: No such file or directory
  NOTE: package pixman-0.22.0-r5.0: task do_distribute_sources: Failed
* "Public Domain" causes sources distributed from "Public" and "Domain"
  folders which is not expected, so use PD as in other recipes
* embryo and epdf had LICENSE defined before inherit efl which
  overwrites it (that's why distribute_sources wasn't failing on their &

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Acked-by: Koen Kooi <koen@dominion.thruhere.net>