qemu-0.12.5: add ncurses, gnutls dependencies
QEmu build breaks occassionally because some of the libraries required
have not been built at the time qemu is being built. I ran into problems
with the "qemu-native" build which tried to link against host libraries
and subsequently failed:

....

|   LINK  sh4eb-softmmu/qemu-system-sh4eb
|   LINK  sh4-softmmu/qemu-system-sh4
|   LINK  mips-softmmu/qemu-system-mips
|   CC    mips64el-softmmu/fpu/softfloat.o
|   CC    sparc-softmmu/i386-dis.o
| /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/libgnutls.so: undefined reference to `gcry_cipher_setkey@GCRYPT_1.2'
| /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/libgnutls.so: undefined reference to `gcry_cipher_setiv@GCRYPT_1.2'
| collect2: ld returned 1 exit status
| make[1]: *** [qemu-system-mips] Error 1
| make: *** [subdir-mips-softmmu] Error 2

....

This patch adds gnutls and ncurses dependencies to the recipe.

Signed-off-by: Thilo Fromm <t.fromm@dresearch.de>
Signed-off-by: Khem Raj <raj.khem@gmail.com>