wvstreams-4.6: Remove dbus support (breaks build)
If wvstreams is configured with DBus support enabled (by not providing
--without-dbus) the the build fails at link time as libdbus cannot be
found:

| ./CXX -c dbus/wvdbusconn
| ./CXX -c dbus/wvdbusmarshal
| ./CXX -c dbus/wvdbusmsg
| ./CXX -c dbus/wvdbusserver
| linking libwvdbus.so...
| arm-angstrom-linux-gnueabi-g++: /libdbus-1.a: No such file or directory
| make: *** [libwvdbus.so] Error 1
| FATAL: oe_runmake failed
NOTE: Task failed: /SCRATCH/maniac/oe-merge-test/OE/tmp.6/work/armv5te-angstrom-linux-gnueabi/wvstreams-4.6-r0/temp/log.do_compile.6422
ERROR: TaskFailed event exception, aborting
ERROR: Build of /home/maniac/work/HYP/oe/3way_merge/recipes/wvstreams/wvstreams_4.6.bb do_compile failed
ERROR: Task 2024 (/home/maniac/work/HYP/oe/3way_merge/recipes/wvstreams/wvstreams_4.6.bb, do_compile) failed

The root cause for this behaviour is in wvstreams' configure.ac; the
weird dbus detection and library path handling breaks successive builds.

This patch, however, does not fix the configure.ac file but disables
DBus support for wvstreams at configure time. This at least fixes the
broken build.

Signed-off-by: Thilo Fromm <t.fromm@dresearch.de>
Acked-by: Paul Menzel <paulepanter@users.sourceforge.net>
Acked-by: Steffen Sledz <sledz@dresearch.de>