proftpd 1.3.3c: add checksums
Task fetch failed with the following error.

	NOTE: This package has no checksums, please add to recipe
	NOTE:
	SRC_URI[md5sum] = "4f2c554d6273b8145095837913ba9e5d"
	SRC_URI[sha256sum] = "44be095ed063df93278928cf665ad7b9b38e2c8d0cca97fb51307ec3a390a591"

	ERROR: proftpd-1.3.3c: ftp://ftp.nl.uu.net/pub/unix/ftp/proftpd/ftp/distrib/source/proftpd-1.3.3c.tar.gz cannot check archive integrity

This is a fix up for commit b3d5cd83 [1].

	commit b3d5cd830628a55e4b4e153191959354e924ec19
	Author: Florian Boor <florian@kernelconcepts.de>
	Date:   Mon Nov 22 11:29:07 2010 +0100

		  proftpd: Add version 1.3.3c

		  Update in order to get rid of several vulnerabilities of previous releases.

		  Signed-off-by: Florian Boor <florian@kernelconcepts.de>

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=b3d5cd830628a55e4b4e153191959354e924ec19

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>