libproxy: Define __USE_BSD before its needed.
This fixed a build break on uclibc where
it complained

armv5te-oe-linux-uclibcgnueabi/usr/include/stdlib.h:215:
error: expected '=', ',', ';', 'asm' or '__attribute__' before 'strtouq'

The reason is
u_quad_t is only defined if __USE_BSD is defined

Signed-off-by: Khem Raj <raj.khem@gmail.com>