wesnoth.inc: fix missing lua5.1 dependency and bump PR
ERROR: Logfile of failure stored in: .../work/i686-angstrom-linux/wesnoth-wvga-1.8.4-r0.1/temp/log.do_configure.28289
Log data follows:
| CMake Error at .../sysroots/x86_64-linux/usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:70 (MESSAGE):
|   Could NOT find Lua51 (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
| Call Stack (most recent call first):
|   .../sysroots/x86_64-linux/usr/share/cmake-2.8/Modules/FindLua51.cmake:72 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
|   CMakeLists.txt:193 (find_package)
|
|
| -- Configuring incomplete, errors occurred!
NOTE: package wesnoth-wvga-1.8.4-r0.1: task do_configure: Failed

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>