glib-2.0_git: do not compile test program `gdbus-serialization`
Task compile fails with the following error message.

	[…]
		CC     gdbus_serialization-gdbus-serialization.o
		CC     gdbus_serialization-gdbus-tests.o
	gdbus-serialization.c:28:23: fatal error: dbus/dbus.h: No such file or directory
	compilation terminated.
	make[5]: *** [gdbus_serialization-gdbus-serialization.o] Error 1
	make[5]: *** Waiting for unfinished jobs....
	make[5]: Leaving directory `/oe/build-minimal-eglibc/shr-dev/work/armv7a-oe-linux-gnueabi/glib-2.0-1_2.29.3-r1+gitr0+d97cbc6731deab137770bc0fe9c69b06f689f5b4/git/gio/tests'
	make[4]: *** [all] Error 2
	[…]

Appyling the same fix as done in commit dd31acda [1]

	commit dd31acda7070e9181f6b6cb63eceee1f93c7cc12
	Author: Eric BENARD <eric@eukrea.com>
	Date:   Thu Dec 30 03:45:53 2010 +0000

		  glib 2.26.1: fix compilation failure

		  during configure, pkgconfig detects dbus-1.pc which was installed
		  by dbus-native and thus the compilation fails because it can't
		  find dbus/dbus.h which is not yet installed for in the target's
		  sysroot.

		  This patch workaround this problem by not compiling the test program
		  which depends on dbus's headers.

		  Signed-off-by: Eric Bénard <eric@eukrea.com>
		  Acked-by: Khem Raj <raj.khem@gmail.com>
		  Acked-by: Martin Jansa <Martin.Jansa@gmail.com>

fixes the error in this case too. This patch is tested using `DISTRO = "shr"` for `MACHINE = "beagleboard"`.

[1] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=7070e9181f6b6cb63eceee1f93c7cc12

Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>